### PR TITLE
Added copper trapdoors and doors to the creative menu

### PR DESCRIPTION
**Pull request by Auxy6858**

### CODE REVIEW

**Comment by DanielMC101** [comment]
it already has it

**Comment by Auxy6858** [comment]
It does?

**Comment by DanielMC101** [comment]
yes, it's only when you enable the 1.21 datapack

**Comment by DanielMC101** [comment]
however tho, there are still some stuff missing like different kinds of tuff blocks, new arrows/potions and new enchanted books.

**Pull request merged**
